#CALCULATION APP
VERSION: 0.0.1
API_LISTEN_ADDRESS: 0.0.0.0:9065
PRODUCTION: false

#POSTGRES DB
PG_ADDR: 10.131.44.22:4000  #35.188.210.113:5432
PG_USER: gbs_flow
PG_PASS: CXd4!KD3Hdh3PWNC
PG_NAME: gbs
PG_DEBUG: false

#EXTERNAL SERVICE
API_ADDRESS: https://sloth-qa.private.linksynergy.com
API_AUTHORIZATION_TOKEN: 'Bearer eyJhbGciOiJSUzI1NiJ9.e'

#REQUEST PARAMS
COMPANY_NAME: 'Rakuten'
DIVISION_US:
  - 'USA'
DIVISION_AU:
  - 'AU'
DIVISION_EU:
  - 'UK'
TAX_ID_US: '13-3967340'
TAX_ID_AU: '79155366215'
TAX_ID_EU: 'GB882755285'
PRODUCT_CLASS: 'ASDE'
TRANSACTION_TYPE: 'SALE'