#CALCULATION APP
VERSION: 0.0.1
API_LISTEN_ADDRESS: 0.0.0.0:9065
PRODUCTION: false

#POSTGRES DB
PG_ADDR: 10.131.44.22:4000  #35.188.210.113:5432
PG_USER: gbs_flow
PG_PASS: CXd4!KD3Hdh3PWNC
PG_NAME: gbs
PG_DEBUG: false

#PABBIT_MQ QUEUE
RABBIT_HOST: 10.131.47.43
RABBIT_PORT: 5672
RABBIT_USER: admin
RABBIT_PASS: admin
RABBIT_VHOST:

RABBIT_CONSUMER_EXCHANGE_NAME: exchange.display.invoice
RABBIT_CONSUMER_QUEUE_NAME: queue.display.invoice.init
RABBIT_CONSUMER_ROUTE_KEY: queue.display.invoice.routeKey

RABBIT_PRODUCER_QUEUE_NAME: queue.display.pdf
RABBIT_PRODUCER_ROUTE_KEY: queue.display.pdf.routeKey


durable D=true
x- -polict=all
#EXTERNAL SERVICE
API_ADDRESS: https://sloth-qa.private.linksynergy.com
API_AUTHORIZATION_TOKEN: 'Bearer eyJhbGciOiJSUzI1NiJ9.e'

#REQUEST PARAMS
COMPANY_NAME: 'Rakuten'

US_REGISTRATION:
  - 'USA'
AU_REGISTRATION:
  - 'AU'
EU_REGISTRATION:
  - 'UK'
TAX_ID_US: '13-3967340'
TAX_ID_AU: '79155366215'
TAX_ID_EU: 'GB882755285'

US_ISO_REGISTRATION: 'US'
AU_ISO_REGISTRATION: 'AU'
EU_ISO_REGISTRATION: 'GB'

PRODUCT_CLASS: 'ASDE'
TRANSACTION_TYPE: 'SALE'